### ISSUE TITLE
Use Felix SCR annotations

### ISSUE THREAD

**Issue by iocanel** [tdiesler/fabric8poc#10]
I think I prefer felix scr annotations mostly because they provide great metatype support, they allow annotating fields and are less ugly when it comes to annotate properties and set default values.

Since they are just used for compile time, I'd pick the ones that feel better when coding.

**Comment by tdiesler** [comment]
Yes, I haven't seen a compelling reason to use the standard either. 
@Reference derives the service type from the method param, which works better when we use ValidatingReference, but other than that ...

**Comment by tdiesler** [comment]
Done
