### ISSUE TITLE
Make ProfileBuilder more friendly.

### ISSUE THREAD

**Issue by iocanel** [tdiesler/fabric8poc#6]
The profile builder needs to be improved and become more friendly / DSL-y

Currently the builder works like this:

``` java
ProfileBuilder.Factory pb = ProfileBuilder.Factory.create(id);
ConfigurationProfileItem item1 = pb.getProfileItemBuilder("id1", ConfigurationProfileItemBuilder.class).setConfiguration(map1);
ConfigurationProfileItem item2 = pb.getProfileItemBuilder("id2", ConfigurationProfileItemBuilder.class).setConfiguration(map2);

Profile p = pb
    .addAttributes(attributes)
    .addProfileItem(item1)
    .addProfileItem(item2)
    .build();
```

With the above approach there are two issues:
i) A lot of boilerplate.
ii) I need to hold a reference of the ProfileBuilder in order to create a ConfigProfileItem and this spoils the DSL-y style of the builder.

Since the builder knows what profile items and profile item builders it supports. It should be like:

``` java
Profile p = ProfileBuilder.Factory.create(id)
    .addAttributes(attributes)
    .addConfiguration("id1", map1)
    .addConfiguration("id2", map2)
    .build();
```

or

``` java
Profile p = ProfileBuilder.Factory.create(id)
    .addAttributes(attributes)
    .addProfileItem(ConfigurationProfileItemBuilder.Factory.create("id1", map1)
    .addProfileItem(ConfigurationProfileItemBuilder.Factory.create("id2", map2)
    .build();
```

I think I prefer the first alternative, or a combination of the two.

**Comment by tdiesler** [comment]
Yes, approach one is good. It encodes the set of possible profile items in the PB signature. We are likely going to have less than a handful PI types, so its ok to have individual methods. The second approach is not so good because it promotes the PIB to a top level thing - it should however be a sub builder, like PI is a subtype of P.

**Comment by tdiesler** [comment]
Resolved
