### ISSUE TITLE
Define an entry level api for clients and internal use

### ISSUE THREAD

**Issue by iocanel** [tdiesler/fabric8poc#9]
Currently we have things like the ProfileManager the ContainerManager etc, but I think that we should have an entry level api for clients and internal use. 

The entry point can directly make use of ProfileManager and ContainerManager etc.
### Excternallyl it could look like:

``` java
FabricConnection fabric = new FabricConnection(url, username, password);
```
### List

``` java
fabric.container().list();
```
### Create:

``` java
fabric.container().newContainer(ChildContainerProvider.class)
                           .id("mycontainer")
                           .parent("root")
                           .version("1.1")
                           .profile("myprofile")
                           .create();
```
### Stop / Destroy a container

``` java
fabric.container().find("mycontainer").stop();
fabric.container().find("mycontainer").destroy();
```

Operate on multiple containers using Predicates (as used in guava and java8) : 

``` java
fabric.container().find(new Predicate<Container>(){ 
    Boolean apply(Container cnt) {
        return cnt.getIdentity().startsWith("broker");
    }
}).stop();
```
### List

``` java
fabric.version().list();
```
### Create

``` java
fabric.version().newVersion().id("1.1.0").create()
```
### Delete

``` java
fabric.version().find("1.1.0").delete()
```
### List Profiles

``` java
fabric.version().find("1.1.0").profiles().list()
```
### Create

``` java
fabric.version().find("1.1.0").newProfile().id("myprofile")
        .addParent("profileA")
        .addConfigItem("my.pid", map)
        .create()
```

**Comment by tdiesler** [comment]
When used in container (where our 1st Level API is available) it would not add functionality - it may provide convenience for the expense of duplicating large parts of the API.

For remote access we currently work with Open MBeans, which indeed are not very convenient to work with. To work with a container, we currently can do

``` java
        ContainerManagement cntManagement = ManagementUtils.getMBeanProxy(mbeanServer, ContainerManagement.OBJECT_NAME, ContainerManagement.class);
        CompositeData cdata = cntManagement.getContainer(idA.getCanonicalForm());
        Container cntB = ContainerOpenType.getContainer(cdata);
        Assert.assertEquals(idA, cntB.getIdentity());
        Assert.assertEquals(cntA.getAttributes(), cntB.getAttributes());
```

I suggest to keep this proposal in mind and perhaps get it started as an additional project one day. In the foreseeable future I suggest to focus on 1st Level API, and a comprehensive set of  MBeans that would need to be available to get something like this implemented anyway.

**Comment by tdiesler** [comment]
Deferred
